//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabryka_Mebli_IO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaMebli_Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListaMebli_Zamowienie()
        {
            this.Zamówienie = new HashSet<Zamówienie>();
        }
    
        public int id { get; set; }
        public int idMebla { get; set; }
        public string Kolor { get; set; }
        public Nullable<int> idListy { get; set; }
        public string Status { get; set; }
        public Nullable<int> pracownikWykonujacy { get; set; }
    
        public virtual Mebel Mebel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamówienie> Zamówienie { get; set; }
    }
}
