//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabryka_Mebli_IO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Pracy
    {
        public Plan_Pracy() { }
        public Plan_Pracy(int idPlanu, int idZam)
        {
            this.idPlanu = idPlanu;
            this.idZamowienie = idZam;
        }
        public int id { get; set; }
        public Nullable<int> idZamowienie { get; set; }
        public Nullable<int> idPlanu { get; set; }
    
        public virtual Zamówienie Zamówienie { get; set; }
    }
}
