//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabryka_Mebli_IO.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdukcjaEntities2 : DbContext
    {
        public ProdukcjaEntities2()
            : base("name=ProdukcjaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BazaZamowien> BazaZamowien { get; set; }
        public virtual DbSet<DaneZamawiajacego> DaneZamawiajacego { get; set; }
        public virtual DbSet<ListaMebli_Zamowienie> ListaMebli_Zamowienie { get; set; }
        public virtual DbSet<Mebel> Mebel { get; set; }
        public virtual DbSet<Plan_Pracy> Plan_Pracy { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zmiany> Zmiany { get; set; }
        public virtual DbSet<Zamówienie> Zamówienie { get; set; }
    }
}
