//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabryka_Mebli_IO.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamówienie()
        {
            this.BazaZamowien = new HashSet<BazaZamowien>();
            this.Plan_Pracy = new HashSet<Plan_Pracy>();
        }
    
        public int id { get; set; }
        public int idZamawiający { get; set; }
        public int idLista { get; set; }
        public Nullable<System.DateTime> DataRealizacji { get; set; }
        public string Status { get; set; }
        public string Kod_Zlecenia { get; set; }
        public Nullable<int> Rodzaj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BazaZamowien> BazaZamowien { get; set; }
        public virtual DaneZamawiajacego DaneZamawiajacego { get; set; }
        public virtual ListaMebli_Zamowienie ListaMebli_Zamowienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Pracy> Plan_Pracy { get; set; }
    }
}
